export enum ActionComicsTypes {
  LOAD_REQUEST = '@characters/LOAD_REQUEST',
  SET_NONE_COMIC = '@characters/SET_NONE_COMIC',
  LOAD_REQUEST_CHARACTER_COMICS = '@characters/LOAD_REQUEST_CHARACTER_COMICS',
  LOAD_REQUEST_CHARACTER_COMICS_SUCCESS = '@characters/LOAD_REQUEST_CHARACTER_COMICS_SUCCESS',
  LOAD_REQUEST_CHARACTER_COMICS_FAILURE = '@characters/LOAD_REQUEST_CHARACTER_COMICS_FAILURE',
}