export enum ActionTypes {
  LOAD_REQUEST = '@characters/LOAD_REQUEST',
  LOAD_SEARCH_REQUEST = '@characters/LOAD_SEARCH_REQUEST',
  LOAD_OREDERBY_REQUEST = '@characters/LOAD_OREDERBY_REQUEST',
  LOAD_SEARCH_OREDERBY_VALUE_REQUEST = '@characters/LOAD_SEARCH_OREDERBY_VALUE_REQUEST',
  LOAD_SUCCESS = '@characters/LOAD_SUCCESS',
  LOAD_FAILURE = '@characters/LOAD_FAILURE',
}